#!/bin/bash

# Mac Mini Audio Wake Fix Installer
# Fixes the issue where audio defaults to built-in speaker after sleep

set -e

echo "=========================================="
echo "Mac Mini Audio Wake Fix Installer"
echo "=========================================="
echo ""

# Check if Homebrew is installed
if ! command -v brew &> /dev/null; then
    echo "❌ Homebrew is not installed."
    echo "   Install it first: https://brew.sh"
    echo "   Run: /bin/bash -c \"\$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)\""
    exit 1
fi

echo "✓ Homebrew found"

# Install SwitchAudioSource if not present
if ! command -v SwitchAudioSource &> /dev/null; then
    echo "→ Installing SwitchAudioSource..."
    brew install switchaudio-osx
else
    echo "✓ SwitchAudioSource already installed"
fi

# Install sleepwatcher if not present
if ! command -v sleepwatcher &> /dev/null; then
    echo "→ Installing sleepwatcher..."
    brew install sleepwatcher
else
    echo "✓ sleepwatcher already installed"
fi

# Show available audio devices
echo ""
echo "=========================================="
echo "Available Audio Output Devices:"
echo "=========================================="
SwitchAudioSource -a -t output
echo ""

# Detect the 3.5mm jack device name (common names)
AUDIO_DEVICE=""
for name in "External Headphones" "Headphones" "Built-in Output" "Line Out"; do
    if SwitchAudioSource -a -t output | grep -q "$name"; then
        AUDIO_DEVICE="$name"
        break
    fi
done

if [ -z "$AUDIO_DEVICE" ]; then
    echo "⚠️  Could not auto-detect 3.5mm audio device."
    echo "   Please enter the exact name from the list above:"
    read -r AUDIO_DEVICE
fi

echo "→ Using audio device: \"$AUDIO_DEVICE\""

# Create the wake script
SCRIPT_DIR="$HOME/.config/audio-wake-fix"
mkdir -p "$SCRIPT_DIR"

cat > "$SCRIPT_DIR/set-audio-output.sh" << EOF
#!/bin/bash
# Audio Wake Fix - Set output to 3.5mm jack
# Generated by install.sh

DEVICE="$AUDIO_DEVICE"
LOG_FILE="$SCRIPT_DIR/audio-wake.log"

# Small delay to let the system fully wake
sleep 2

# Log the event
echo "\$(date): Woke from sleep, checking for audio device: \$DEVICE" >> "\$LOG_FILE"

# Check if the headphone device is available (i.e., something is plugged in)
if /opt/homebrew/bin/SwitchAudioSource -a -t output | grep -q "\$DEVICE"; then
    echo "\$(date): Device '\$DEVICE' detected, switching audio output" >> "\$LOG_FILE"

    # Set the audio output
    /opt/homebrew/bin/SwitchAudioSource -s "\$DEVICE" -t output 2>> "\$LOG_FILE"

    # Verify
    CURRENT=\$(/opt/homebrew/bin/SwitchAudioSource -c -t output)
    echo "\$(date): Current output is now: \$CURRENT" >> "\$LOG_FILE"
else
    echo "\$(date): Device '\$DEVICE' not detected (nothing plugged in), skipping audio switch" >> "\$LOG_FILE"
fi

# Keep log file manageable (last 100 lines)
tail -100 "\$LOG_FILE" > "\$LOG_FILE.tmp" && mv "\$LOG_FILE.tmp" "\$LOG_FILE"
EOF

chmod +x "$SCRIPT_DIR/set-audio-output.sh"
echo "✓ Created wake script at $SCRIPT_DIR/set-audio-output.sh"

# Create sleepwatcher wakeup hook
ln -sf "$SCRIPT_DIR/set-audio-output.sh" "$HOME/.wakeup"
echo "✓ Created ~/.wakeup symlink"

# Create LaunchAgent for sleepwatcher
LAUNCH_AGENTS_DIR="$HOME/Library/LaunchAgents"
mkdir -p "$LAUNCH_AGENTS_DIR"

cat > "$LAUNCH_AGENTS_DIR/com.audio-wake-fix.sleepwatcher.plist" << EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>com.audio-wake-fix.sleepwatcher</string>
    <key>ProgramArguments</key>
    <array>
        <string>/opt/homebrew/sbin/sleepwatcher</string>
        <string>-V</string>
        <string>-w</string>
        <string>$HOME/.wakeup</string>
    </array>
    <key>RunAtLoad</key>
    <true/>
    <key>KeepAlive</key>
    <true/>
</dict>
</plist>
EOF

echo "✓ Created LaunchAgent"

# Load the LaunchAgent
launchctl unload "$LAUNCH_AGENTS_DIR/com.audio-wake-fix.sleepwatcher.plist" 2>/dev/null || true
launchctl load -w "$LAUNCH_AGENTS_DIR/com.audio-wake-fix.sleepwatcher.plist"
echo "✓ Loaded LaunchAgent"

echo ""
echo "=========================================="
echo "✅ Installation Complete!"
echo "=========================================="
echo ""
echo "The fix is now active. Your Mac will automatically"
echo "switch to \"$AUDIO_DEVICE\" after waking from sleep."
echo ""
echo "Logs are stored at: $SCRIPT_DIR/audio-wake.log"
echo ""
echo "To test: Put your Mac to sleep, wake it, and check"
echo "that audio plays through your external speakers."
echo ""
echo "To uninstall, run: ./uninstall.sh"
